packages:
  - apps/*
  - packages/*

catalog:
  '@prisma/client': ^7.2.0
  '@trpc/client': ^11.7.2
  '@trpc/server': ^11.7.2
  better-auth: ^1.4.18
  dotenv: ^17.3.1
  next: ^16.1.1
  typescript: ^5.9.3
  zod: ^4.3.6

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - lefthook
  - msgpackr-extract
  - msw
  - prisma
  - sharp
